config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :countries
  resources :venues
  resources :categories
  resources :artist_types

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete "remove_user_avatar", to: "registrations#remove_avatar", as: :remove_user_avatar
    post "create_news_item", to: "registrations#create_news_item", as: :create_news_item
    patch "update_news_item", to: "registrations#update_news_item", as: :update_news_item
    delete "destroy_news_item/:id", to: "registrations#destroy_news_item", as: :destroy_news_item
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  get "events_category/:category", to: "events#events_category", as: :events_category
  get "events_filter", to: "events#index", as: :events_filter
  get "events_manager_filter", to: "events_manager#index", as: :events_manager_filter

  get "list_categories", to: "categories#index", defaults: { format: "json" }
  get "list_categories/:parent_category", to: "categories#index", defaults: { format: "json" }

  get "statistics", to: "stats#index"

  resources :events do
    resources :gallery_images
  end

  resources :events_manager, controller: "events_manager" do
    resources :gallery_images
    post "update_featured", to: "events_manager#update_featured", as: :update_featured
    post "update_published", to: "events_manager#update_published", as: :update_published
    post "update_approval_message", to: "events_manager#update_approval_message", as: :update_approval_message
  end

  resources :users_manager, controller: "users_manager" do
    post "update_accept_message", to: "users_manager#update_accept_message", as: :update_accept_message
  end

  resources :admin, controller: "admin"

  resources :social, controller: "social", only: [:index, :show] do
    patch "comment_news_item", to: "social#comment_news_item", as: :comment_news_item
    patch "comment_event", to: "social#comment_event", as: :comment_event
    patch "update_comment", to: "social#update_comment", as: :update_comment
  end

  resources :likenewsitemships
  resources :friendships
  resources :fanships

end

app/models/event.rb
class Event < ActiveRecord::Base
  include ClassyEnum::ActiveRecord

  has_paper_trail

  scope :ordered, -> { order(title: :asc) }

  classy_enum_attr :approved, default: "editing"

  validates :title, presence: true, length: { minimum: 5, maximum: 80 }, unless: :has_parent?
  validates :title, uniqueness: { case_sensitive: false, message: I18n.t(:'errors.messages.event.title'), conditions: -> { where(parent: nil) } }, unless: :has_parent?

  validates :subtitle, length: { maximum: 100 }

  validates :short_description, :description, presence: true, unless: :has_parent?

  validates :start_date, :start_time, presence: true, if: "!group?"

  validates :start_date, date: { after_or_equal_to: Proc.new { Date.today }, message: I18n.t(:'errors.messages.event.date') }, unless: "start_date.nil?"
  validates :start_date, date: { before_or_equal_to: :end_date, message: I18n.t(:'errors.messages.event.start_date') }, unless: "end_date.nil?"

  validates :end_date, date: { after_or_equal_to: Proc.new { Date.today }, message: I18n.t(:'errors.messages.event.date') }, unless: "end_date.nil?"
  validates :end_date, date: { after_or_equal_to: :start_date, message: I18n.t(:'errors.messages.event.end_date') }, unless: "end_date.nil?"

  validates :short_description, length: { minimum: 80, maximum: 500 }, unless: :has_parent?
  validates :description, length: { minimum: 200, maximum: 3000 }, unless: :has_parent?

  belongs_to :category
  validates :category, presence: true, unless: :has_parent?

  belongs_to :venue
  validates :venue, presence: true, if: "!group? && (!has_parent? || (has_parent? && parent.get_venue_validation.nil?))"

  belongs_to :user

  mount_uploader :title_image, TitleImageUploader
  validates :title_image, presence: true, unless: :has_parent?

  has_many :subevents, class_name: "Event", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent, class_name: "Event"

  has_many :gallery_images, dependent: :destroy
  accepts_nested_attributes_for :gallery_images, allow_destroy: true

  has_many :performships
  has_many :performers, :through => :performships, :source => :user
  accepts_nested_attributes_for :performships

  has_one :approval_message, dependent: :destroy
  accepts_nested_attributes_for :approval_message, allow_destroy: true

  has_many :comments, class_name: "NewsItem", foreign_key: "event_id", dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true

  auto_html_for :video do
    youtube(width: 350, height: 250, autoplay: false)
    vimeo(width: 350, height: 250, autoplay: false)
  end

  acts_as_taggable

  def has_tag?(tag)
    tag_list.include?(tag)
  end

  def has_parent?
    if parent == nil
      return false
    else
      return true
    end
  end

  def is_base_event?
    !has_parent?
  end

  def get_title
    if title != nil && title != ""
      title
    else
      parent.get_title
    end
  end

  def get_full_title
    if parent != nil
      if title != nil && title != ""
        parent.get_full_title + " / " + title
      else
        parent.get_full_title
      end
    else
      title
    end
  end

  def format_title
    if title != nil && title != ""
      title
    elsif start_date != nil && start_time != nil
      format_start_date_time
    else
      t = get_start_datetime
      if t != nil
        I18n.l t, format: :date_and_time_long
      else
        I18n.t(:"errors.unknown")
      end
    end
  end

  def get_subtitle
    if subtitle != nil && subtitle != ""
      subtitle
    else
      parent.get_subtitle
    end
  end

  def get_category
    if category_id != nil
      Category.with_deleted.find(category_id)
    else
      parent.get_category
    end
  end

  def get_venue_validation
    if venue != nil
      venue
    elsif parent != nil
      parent.get_venue_validation
    else
      nil
    end
  end

  def get_venue
    if venue_id != nil
      Venue.with_deleted.find(venue_id)
    elsif parent != nil
      parent.get_venue
    else
      nil
    end
  end

  def get_title_image
    if title_image.present?
      title_image
    elsif parent != nil
      parent.get_title_image
    else
      nil
    end
  end

  def get_start_datetime
    if start_date != nil && start_time != nil
      DateTime.parse(format_start_date_time_uni)
    elsif subevents != nil && subevents.count > 0
      subevents.sort_by { |ev| ev.get_start_datetime }.first.get_start_datetime
    else
      nil
    end
  end

  def markdown_short_description
    if short_description != nil
      Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(short_description)
    end
  end

  def markdown_description
    if description != nil
      Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(description)
    end
  end

  def format_start_date_time
    if start_date != nil && start_time != nil
      (I18n.l start_date, format: :date_only).concat(", ").concat(I18n.l start_time, format: :time_only)
    else
      ""
    end
  end

  def format_start_date_time_uni
    if start_date != nil && start_time != nil
      (I18n.l start_date, format: :date_only_uni).concat(" ").concat(I18n.l start_time, format: :time_only_uni)
    else
      ""
    end
  end

  def format_end_date_time
    formatted = ""
    if end_date != nil
      formatted.concat((I18n.l end_date, format: :date_only))
    end
    if end_time != nil
      formatted.concat(", ").concat(I18n.l end_time, format: :time_only)
    end
    formatted
  end

  def belongs_to_user(u)
    return (u == user && (parent == nil || parent.belongs_to_user(u))) || u.is_admin?
  end

  def is_visible?
    if parent == nil
      !private && published && approved == :is_approved && get_start_datetime != nil
    else
      parent.is_visible?
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [ :show ]

  before_action :authenticate_user!, except: [:index, :show, :events_category]

  layout "application"

  def index
    @events = filter_visible_events(filter_base_events(Event.all.ordered)).select { |e| e.start_date >= Date.today }
    #@category = params[:category]
    #@tag = params[:tag]

    #if @category != nil
    #  @category = Category.find_by_name(@category)
    #  @events = @events.select { |e| e.category.is_category?(@category) }
    #end

    #if @tag != nil
    #  @events = @events.select { |e| e.has_tag?(@tag) }
    #end

    @events = @events.sort { |a,b| a.title.downcase <=> b.title.downcase }
    @events_featured = @events.select { |e| e.featured == true }
    @events_nearest = @events.sort { |a,b| a.start_date <=> b.start_date }
    @events_newest = @events.sort { |a,b| b.id <=> a.id }

    @events_category = Hash.new

    Category.where(parent: nil).each do |c|
      ev_cat = @events.select { |e| e.category.is_category?(c) }
      ev_cat_hash = Hash.new
      ev_cat_hash["all"] = ev_cat
      ev_cat_hash["featured"] = ev_cat.select { |e| e.featured == true }
      ev_cat_hash["nearest"] = ev_cat.sort { |a,b| a.start_date <=> b.start_date }
      ev_cat_hash["newest"] = ev_cat.sort { |a,b| b.id <=> a.id }
      ev_cat_hash["popular"] = ev_cat.sort { |a,b| b.viewed <=> a.viewed }
      ev_cat_hash["subcategories"] = Hash.new
      @events_category[c.name] = ev_cat_hash

      Category.where(parent: c).each do |subc|
        ev_subcat = @events.select { |e| e.category.is_category?(subc) }
        ev_subcat_hash = ev_cat_hash["subcategories"]
        ev_subcat_hash[subc.name] = Hash.new
        ev_subcat_hash[subc.name]["all"] = ev_subcat
        ev_subcat_hash[subc.name]["featured"] = ev_subcat.select { |e| e.featured == true }
        ev_subcat_hash[subc.name]["nearest"] = ev_subcat.sort { |a,b| a.start_date <=> b.start_date }
        ev_subcat_hash[subc.name]["newest"] = ev_subcat.sort { |a,b| b.id <=> a.id }
        ev_subcat_hash[subc.name]["popular"] = ev_subcat.sort { |a,b| b.viewed <=> a.viewed }
      end
      @events_category[c.name] = ev_cat_hash
    end
  end

  def events_category
    @category = Category.with_deleted.find_by_name(params[:category])

    @events = filter_visible_events(filter_base_events(Event.all.ordered)).select { |e| e.start_date >= Date.today }.select { |e| e.category.is_category?(@category) }

    @events_featured = @events.select { |e| e.featured == true }
  end

  def show
    if @event == nil
      flash[:alert] = I18n.t(:"pundit.not_authorized_to_show_event")
      redirect_to root_path
    end
  end

  private

    def find_event
      if user_signed_in? && current_user.is_admin?
        @event = Event.find(params[:id])
      elsif user_signed_in? && current_user.is_organizer?
        @event = Event.find(params[:id])

        if !@event.belongs_to_user(current_user) && !@event.is_visible?
          @event = nil
        end
      else
        @event = filter_visible_events(Event.all.ordered).select { |e| e.id.to_s == params[:id] }
        if @event != nil
          @event = @event.first
        end
      end
    end

    def filter_base_events(events)
      events.select { |e| !e.has_parent? }
    end

    def filter_visible_events(events)
      events.select { |e| e.is_visible? }
    end

end

app/helpers/events_helper.rb
module EventsHelper
  def format_date_time(date_time)
    I18n.l date_time.in_time_zone("CET"), format: :date_and_time
  end
end

app/views/events/admin/_print.html.erb
<% if event.published %>
  <div id="popup-approve-event-<%= event.id %>" class="reveal-modal small" data-reveal>
    <%= render "events/approve", event: @event %>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  </div>
<% end %>

<br>

<div class="row">
  <div class="medium-14 columns">
    <nav class="breadcrumbs">
      <%= link_to "Všetky udalosti", events_manager_index_path %>
      <%= raw event.get_category.split_name.map { |n| link_to Category.translate_name(n), events_manager_filter_path(category: n, tag: @tag, approved: @approved) }.join("") %>
    </nav>
  </div>
</div>

<div class="row">
  <div class="medium-14 columns">
    <h1><%= event.get_title %>
      <% if event.published %>
        <span class="label success" style="position: relative; top: -10px;">Publikované</span>
      <% else %>
        <span class="label alert" style="position: relative; top: -10px;">Nepublikované</span>
      <% end %>
      <% if event.approved == :is_approved %>
        <span class="label success" style="position: relative; top: -10px;"><%= event.approved.text %></span>
      <% else %>
        <span class="label alert" style="position: relative; top: -10px;"><%= event.approved.text %></span>
      <% end %>
      <% if event.featured %>
        <span class="label notice" style="position: relative; top: -10px;">Odporúčané</span>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="medium-4 columns">
    <% if event.get_title_image %>
      <!-- <p>Titulný obrázok:</p> -->
        <%= image_tag event.get_title_image.url, :style => "width: 350px; height: 350px;" %>
    <% end %>
    <ul class="st-list-unstyled">
    <% if event.format_end_date_time != "" %>
      <li>Začiatok udalosti: <%= event.format_start_date_time %></li>
      <li>Koniec udalosti: <%= event.format_end_date_time %></li>
    <% else %>
      <li>Dátum a čas: <%= event.format_start_date_time %></li>
    <% end %>
    <li>Miesto konania: <%= event.get_venue != nil ? event.get_venue : t(:"venue.more_venues") %></li>

    <% if event.get_venue != nil %>
      <li><div id="map" style='width: 350px; height: 200px;'></div></li>

      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({
          provider: {
            disableDefaultUI: true,
            mapTypeId: google.maps.MapTypeId.ROADMAP
            // pass in other Google Maps API options here
            },
          internal: {
            id: 'map'
          }
        },
        function() {
          markers = handler.addMarkers([{
              "lat": <%= event.get_venue.get_lat %>,
              "lng": <%= event.get_venue.get_lng %>,
              "infowindow": "<%= event.get_venue.format_name %>"
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(13);

            google.maps.event.trigger(markers[0].serviceObject, 'click');
          }
        );
      </script>
    <% end %>
    <li>Vystupujúci: <%= raw event.performers.map { |p| link_to p.get_name, social_path(p) }.join(", ") %></li>
    <li>Súkromná udalosť: <%= event.private ? "áno" : "nie"  %></li>
    <li>Skupina: <%= event.group ? "áno" : "nie"  %></li>
    <% if event.group %>
      <p>Podudalosti (<%= event.subevents.count %>):</p>
      <% event.subevents.select { |ev| ev.get_start_datetime != nil }.sort_by { |ev| ev.get_start_datetime }.each do |e| %>
        <p><%= link_to e.format_title, events_manager_path(e) %></p>
      <% end %>
      <% event.subevents.select { |ev| ev.get_start_datetime == nil }.each do |e| %>
        <p><%= link_to "skupina bez podudalostí", events_manager_path(e) %></p>
      <% end %>
      <p><%= link_to "Pridať udalosť", new_events_manager_path(parent: event), class: "button tiny radius" %></p>
      <p><%= link_to "Pridať skupinu", new_events_manager_path(parent: event, group: true), class: "button tiny radius" %></p>
    <% end %>
    <li>Vstupenky: 450 (Voľné: 210)</li>
    <li>Návštevníci</li>
    <li>Štatistika eventu</li>
    <li>Tagy: <%= raw event.tag_list.map { |t| link_to t, events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: t, approved: @approved) }.join(", ") %></li>
  </ul>
  </div>
  <div class="medium-7 columns">
    <h4><%= event.subtitle %></h4>
    <p><%= raw event.markdown_short_description %></p>
    <p><%= raw event.markdown_description %></p>
    <hr>
    <ul class="clearing-thumbs st-list-unstyled" data-clearing>
      <% unless event.gallery_images.empty? %>
        <% event.gallery_images.each do |img| %>
          <li>
            <%= link_to image_tag(img.gallery_image.url(:thumb), data: { caption: img.format_description }), img.gallery_image.url, class: "th" %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <hr>
    <div class="flex-video"><%= event.video_html %></div>
  </div>

 <div class="medium-3 columns">
    <div class="panel callout">
      <ul class="st-list-unstyled" style="font-size: 0.8em;">
        <li>Zobrazení: <%= event.viewed %></li>
        <li>Vytvorené: <%= format_date_time(event.created_at) %></li>
        <!-- <li>Posledná aktualizácia: <%= event.updated_at %></li> -->
        <li>História úprav (nezahŕňa titulný obrázok, tagy, galériu, vystupujúcich, podudalosti)</li>
        <li>
          <ul id="changes-history" class="st-list-unstyled" style="font-size: 1.0em;">
            <% i = 0 %>
            <% event.versions.each do |e| %>
              <% if i > 0 %>
                <li><%= link_to i.to_s + ": " + format_date_time(e.created_at), events_manager_path(event, version_id: e.id) %></li>
              <% end %>
              <% i += 1 %>
            <% end %>
            <li><%= link_to "aktuálna verzia", events_manager_path(event) %></li>
          </ul>
        </li>
      </ul>
      <ul class="st-list-unstyled stack button-group">
        <li><%= link_to "Zobraziť ako používateľ", event_path(event), target: "_blank", class: "button tiny" %></li>
        <li><%= link_to "Upraviť", edit_events_manager_path(event), class: "button tiny primary st-adjust-bottom" %></li>
        <li><%= link_to "Odstrániť", events_manager_path(event), class: "button tiny alert st-adjust-bottom", method: :delete, data: { confirm: "Naozaj chcete odstrániť túto udalosť?" } %></li>

        <li>
          <%= simple_form_for(event, url: events_manager_update_featured_path(event), html: { method: :post }) do |f| %>
            <% if event.featured %>
              <%= f.hidden_field :featured, value: false %>
              <%= f.submit "Zrušiť odporúčanie", class: "button tiny alert st-full-width" %>
            <% else %>
              <%= f.hidden_field :featured, value: true %>
              <%= f.submit "Odporúčať", class: "button tiny success st-full-width" %>
            <% end %>
          <% end %>
        </li>

        <li>
          <%= simple_form_for(event, url: events_manager_update_published_path(event), html: { method: :post }) do |f| %>
            <% if event.published %>
              <%= f.hidden_field :published, value: false %>
              <%= f.submit "Zrušiť publikovanie", class: "button tiny alert st-full-width" %>
            <% else %>
              <%= f.hidden_field :published, value: true %>
              <%= f.submit "Publikovať", class: "button tiny success st-full-width" %>
            <% end %>
          <% end %>
        </li>

        <% if event.published %>
          <li><a href="#" class="tiny button" data-reveal-id="popup-approve-event-<%= event.id %>">Schváliť/neschváliť</a></li>
        <% end %>
      </ul>
    </div>
  </div>

  <% if event.approval_message != nil %>
    <div class="medium-14 columns">
      <h4>Schvaľovacia správa</h4>
      <p>Posledná úprava: <%= l event.approval_message.updated_at, format: :date_and_time %></p>
      <p><%= raw event.approval_message.markdown_content %></p>
    </div>
  <% end %>

</div>

app/views/events/admin/_print_short.html.erb
<% if event.published %>
  <div id="popup-approve-event-<%= event.id %>" class="reveal-modal small" data-reveal>
    <%= render "events/approve", event: event %>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  </div>
<% end %>

<div class="panel">

<div class="row">
  <div class="medium-14 columns">
    <h3>
      <%= link_to event.title, events_manager_path(event) %>
      <% if event.published %>
        <span class="label success" style="position: relative; top: -10px;">Publikované</span>
      <% else %>
        <span class="label alert" style="position: relative; top: -10px;">Nepublikované</span>
      <% end %>
      <% if event.approved == :is_approved %>
        <span class="label success" style="position: relative; top: -10px;"><%= event.approved.text %></span>
      <% else %>
        <span class="label alert" style="position: relative; top: -10px;"><%= event.approved.text %></span>
      <% end %>
      <% if event.featured %>
        <span class="label notice" style="position: relative; top: -10px;">Odporúčané</span>
      <% end %>
    </h3>
  </div>
</div>

<div class="row">
  <div class="medium-14 columns">
    <% if event.subtitle? %>
      <h5><%= event.subtitle %></h5>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="medium-14 columns">
    <ul class="st-list-unstyled" style="margin-bottom: 0;">
      <% if event.format_end_date_time != "" %>
        <li>Začiatok udalosti: <%= event.format_start_date_time %></li>
        <li>Koniec udalosti: <%= event.format_end_date_time %></li>
        <li><%= event.get_venue != nil ? event.get_venue : t(:"venue.more_venues") %> | Zobrazení: <%= event.viewed %> | <%= link_to User.with_deleted.find(event.user_id).get_name, users_manager_path(event.user_id) %></li>
      <% else %>
        <li><%= event.format_start_date_time %> | <%= event.get_venue != nil ? event.get_venue : t(:"venue.more_venues") %> | Zobrazení: <%= event.viewed %> | <%= link_to User.with_deleted.find(event.user_id).get_name, users_manager_path(event.user_id) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row" style="margin-top: 10px;">
  <div class="medium-4 columns">
    <% if event.title_image.present? %>
      <%= link_to events_manager_path(event) do %>
        <%= image_tag event.title_image.url(:thumb), :style => "width: 200px; height: 200px;", class: "th" %>
      <% end %>
    <% end %>
  </div>
  <div class="medium-10 columns">

    <p><%= raw event.markdown_short_description %></p>
    <ul class="st-list-unstyled">

    <li>Kategória: <%= raw Category.with_deleted.find(event.category_id).split_name.map { |n| link_to Category.translate_name(n), events_manager_filter_path(category: n, tag: @tag, approved: @approved) }.join(" / ") %></li>
    <li>Tagy: <%= raw event.tag_list.map { |t| link_to t, events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: t, approved: @approved)  }.join(", ") %></li>
    </ul>

    <ul class="st-list-unstyled st-list-inline">
      <li><%= link_to "Zobraziť", events_manager_path(event), class: "button tiny" %></li>
      <li><%= link_to "Upraviť", edit_events_manager_path(event), class: "button tiny success" %></li>
      <li><%= link_to "Odstrániť", events_manager_path(event, category: @category != nil ? @category.name : nil, tag: @tag, approved: @approved), class: "button tiny alert", method: :delete, data: { confirm: "Naozaj chcete odstrániť túto udalosť?" } %></li>

      <li>
        <%= simple_form_for(event, url: events_manager_update_published_path(event, category: @category != nil ? @category.name : nil, tag: @tag, approved: @approved), html: { method: :post }) do |f| %>
          <% if event.published %>
            <%= f.hidden_field :published, value: false %>
            <%= f.submit "Zrušiť publikovanie", class: "button tiny alert st-full-width" %>
          <% else %>
            <%= f.hidden_field :published, value: true %>
            <%= f.submit "Publikovať", class: "button tiny success st-full-width" %>
          <% end %>
        <% end %>
      </li>

      <% if event.published %>
        <li><a href="#" class="tiny button" data-reveal-id="popup-approve-event-<%= event.id %>">Schváliť/neschváliť</a></li>
      <% end %>
    </ul>
  </div>
</div>
</div>

<!-- <div class="row">
  <p>Rozšírený popis: <%= raw event.markdown_description %></p>
</div> -->

app/views/events/admin/edit.html.erb
<div class="row">
  <h1>Upraviť <%= @event.group ? "skupinu" : "udalosť" %></h1>
</div>

<div class="row">
  <div class="medium-14 columns">
    <%= render "events/admin/form" %>
  </div>
</div>

app/views/events/admin/index.html.erb
<br>

<div class="row">

  <div class="medium-10 columns">

    <div class="row">
      <div class="medium-14 columns">
        <ul class="button-group even-3">
          <%= render "categories/dropdown_menu", category: @category %>
        </ul>
      </div>
    </div>

    <%= render "categories/dropdown_menu_contents", category: @category %>

    <div class="row">
      <div class="medium-14 columns">
        <dl class="sub-nav" style="background-color: #f2f2f2; padding: 10px 10px 10px 0;">
          <dt>Filter:</dt>
          <%= raw (@approved == nil ? "<dd class=\"active\">" : "<dd>") %><%= link_to "Všetky udalosti " + " (" + @events_wo_approved.count.to_s + ")", events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: @tag, approved: nil) %></dd>
          <%= raw (@approved == :editing.to_s ? "<dd class=\"active\">" : "<dd>") %><%= link_to t("classy_enum.approved.editing") + " (" + @events_wo_approved.select { |e| e.approved == :editing }.count.to_s + ")", events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: @tag, approved: :editing) %></dd>
          <%= raw (@approved == :waiting_for_approval.to_s ? "<dd class=\"active\">" : "<dd>") %><%= link_to t("classy_enum.approved.waiting_for_approval") + " (" + @events_wo_approved.select { |e| e.approved == :waiting_for_approval }.count.to_s + ")", events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: @tag, approved: :waiting_for_approval) %></dd>
          <%= raw (@approved == :is_not_approved.to_s ? "<dd class=\"active\">" : "<dd>") %><%= link_to t("classy_enum.approved.is_not_approved") + " (" + @events_wo_approved.select { |e| e.approved == :is_not_approved }.count.to_s + ")", events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: @tag, approved: :is_not_approved) %></dd>
          <%= raw (@approved == :is_approved.to_s ? "<dd class=\"active\">" : "<dd>") %><%= link_to t("classy_enum.approved.is_approved") + " (" + @events_wo_approved.select { |e| e.approved == :is_approved }.count.to_s + ")", events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: @tag, approved: :is_approved) %></dd>
        </dl>
      </div>
    </div>

    <div class="row">
      <div class="medium-14 columns">
        <% @events.each do |event| %>
          <%= render "events/admin/print_short", event: event %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="row">
      <div class="medium-14 columns">
        <%= link_to "Vytvoriť udalosť", new_events_manager_path, class: "button expand small primary" %>
        <%= link_to "Vytvoriť skupinu", new_events_manager_path(group: true), class: "button expand small primary" %>
      </div>
    </div>
    <div class="row">
      <div class="medium-14 columns">
        <div id="tag_cloud">
          <p>Tagy:<br/>
            <% tag_cloud Event.tag_counts, %w[s m l xl] do |tag, css_class| %>
              <%= link_to tag.name, events_manager_filter_path(category: @category != nil ? @category.name : nil, tag: tag.name, approved: @approved), class: css_class %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/admin/new.html.erb
<div class="row">
  <div class="medium-14 columns">
    <h1>Vytvoriť  <%= @event.group ? "skupinu" : "udalosť" %></h1>
  </div>
</div>

<div class="row">
  <div class="medium-14 columns">
    <%= render "events/admin/form" %>
  </div>
</div>

app/views/events/admin/show.html.erb
<div class="row">
  <% @title = "SmartTicket" %>
</div>

<%= render "events/admin/print", event: @event %>

<div class="row">
  <%= link_to "Všetky udalosti", events_manager_index_path, class: "button tiny radius" %>
</div>