config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :countries
  resources :venues
  resources :categories
  resources :artist_types

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete "remove_user_avatar", to: "registrations#remove_avatar", as: :remove_user_avatar
    post "create_news_item", to: "registrations#create_news_item", as: :create_news_item
    patch "update_news_item", to: "registrations#update_news_item", as: :update_news_item
    delete "destroy_news_item/:id", to: "registrations#destroy_news_item", as: :destroy_news_item
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  get "events_category/:category", to: "events#events_category", as: :events_category
  get "events_filter", to: "events#index", as: :events_filter
  get "events_manager_filter", to: "events_manager#index", as: :events_manager_filter

  get "list_categories", to: "categories#index", defaults: { format: "json" }
  get "list_categories/:parent_category", to: "categories#index", defaults: { format: "json" }

  get "statistics", to: "stats#index"

  resources :events do
    resources :gallery_images
  end

  resources :events_manager, controller: "events_manager" do
    resources :gallery_images
    post "update_featured", to: "events_manager#update_featured", as: :update_featured
    post "update_published", to: "events_manager#update_published", as: :update_published
    post "update_approval_message", to: "events_manager#update_approval_message", as: :update_approval_message
  end

  resources :users_manager, controller: "users_manager" do
    post "update_accept_message", to: "users_manager#update_accept_message", as: :update_accept_message
  end

  resources :admin, controller: "admin"

  resources :social, controller: "social", only: [:index, :show] do
    patch "comment_news_item", to: "social#comment_news_item", as: :comment_news_item
    patch "comment_event", to: "social#comment_event", as: :comment_event
    patch "update_comment", to: "social#update_comment", as: :update_comment
  end

  resources :likenewsitemships
  resources :friendships
  resources :fanships

end

app/models/user.rb
class User < ActiveRecord::Base
  include ClassyEnum::ActiveRecord

  scope :users, -> { where(role: :user) }
  scope :organizers, -> { where(role: :organizer) }
  scope :artists, -> { where(role: :artist) }
  scope :admins, -> { where(role: :admin) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :lockable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  attr_accessor :login


  # Common fields
  validates :email, email: true

  classy_enum_attr :role, default: "user"

  mount_uploader :avatar, AvatarUploader

  belongs_to :country

  has_many :news_items, dependent: :destroy
  accepts_nested_attributes_for :news_items, allow_destroy: true

  acts_as_paranoid


  # User fields
  validates :date_of_birth, date: { before_or_equal_to: Proc.new { Date.today }, message: I18n.t(:'errors.messages.user.date_of_birth') }, unless: "date_of_birth.nil?"

  classy_enum_attr :sex, allow_blank: true, default: ""

  has_many :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> { where(friendships: { accepted: true}) }, :through => :friendships, :source => :friend
  has_many :inverse_friends, -> { where(friendships: { accepted: true}) }, :through => :inverse_friendships, :source => :user
  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, :through => :friendships, :source => :friend
  has_many :requested_friends, -> { where(friendships: { accepted: false}) }, :through => :inverse_friendships, :source => :user

  has_many :inverse_fanships, class_name: "Fanship", foreign_key: "fan_id"
  has_many :inverse_fans, :through => :inverse_fanships, :source => :user


  # Organizer fields
  has_many :events


  # Artist fields
  validates :name, presence: true, length: { minimum: 2, maximum: 80 }, if: "is_artist?"

  validates :short_description, length: { maximum: 500 }, if: "is_artist?"
  validates :description, length: { maximum: 3000 }, if: "is_artist?"

  has_many :memberships
  has_many :inverse_memberships, class_name: "Membership", foreign_key: "member_id"

  has_many :members, :through => :memberships, :source => :member
  has_many :inverse_members, :through => :inverse_memberships, :source => :user

  accepts_nested_attributes_for :memberships

  has_many :performships
  has_many :perform_events, :through => :performships, :source => :event

  belongs_to :artist_type


  # User and organizer fields
  validates :nickname, presence: true, uniqueness: { case_sensitive: false }, if: "is_user? || is_organizer?"


  # User and artist fields
  has_many :likecategoryships
  has_many :likecategories, :through => :likecategoryships, :source => :category
  accepts_nested_attributes_for :likecategoryships


  # Organizer and artist fields
  has_many :fanships
  has_many :fans, :through => :fanships, :source => :fan

  has_one :accept_message, dependent: :destroy
  accepts_nested_attributes_for :accept_message, allow_destroy: true


  def login=(login)
    @login = login
  end

  def login
    @login || self.nickname || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(nickname) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.facebook_from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.extra.raw_info.first_name
      user.surname = auth.extra.raw_info.last_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.uid = auth.uid
      user.provider = auth.provider
    end
  end

  def self.google_from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.first_name
      user.surname = auth.info.last_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.uid = auth.uid
      user.provider = auth.provider
    end
  end

  def age
    if date_of_birth != nil
      now = Time.now.to_date
      now.year - date_of_birth.year - (date_of_birth.to_date.change(:year => now.year) > now ? 1 : 0)
    end
  end

  def is_correct_real_name?
    (name != nil && name != "") && (surname != nil && surname != "")
  end

  def get_show_name
    if nickname != nil && nickname != ""
      nickname
    else
      if name != nil && name != ""
        name
      else
        email
      end
    end
  end

  def get_name
    if show_real_name && is_correct_real_name?
      name.to_s + " " + surname.to_s
    else
      get_show_name
    end
  end

  def get_sort_name
    if show_real_name && is_correct_real_name?
      surname.to_s
    else
      get_show_name
    end
  end

  def is_parent?(searched_parent)
    if inverse_members == nil || inverse_members == [] || searched_parent == nil
      false
    elsif inverse_members.select { |m| m.id == searched_parent.id } != nil && inverse_members.select { |m| m.id == searched_parent.id } != []
      true
    else
      inverse_members.each do |m|
        return true if m.is_parent?(searched_parent)
      end
      false
    end
  end

  def is_email_empty?
    return email == ""
  end

  def markdown_short_description
    if short_description != nil
      Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(short_description)
    end
  end

  def markdown_description
    if short_description != nil
      Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(description)
    end
  end

  def friends
    active_friends | inverse_friends
  end

  def likeorganizers
    inverse_fans.select{ |u| u.is_organizer? }
  end

  def likeartists
    inverse_fans.select{ |u| u.is_artist? }
  end

  Role.all.each do |r|
    define_method "is_#{r.to_s}?" do
      role == :"#{r.to_s}"
    end
  end

end

app/views/users/_accept.html.erb
<% hint = t(:"simple_form.hints.accept_message.content") %>
<% accept_message_css_class = "user-accept-message-content-" + user.id.to_s %>

<script type="text/javascript">
$(function() {
  var input_selector = '#user_accept_message_attributes_content.user-accept-message-content-<%= user.id %>';
  var mdhtmlform_selector = '#mdhtmlform-user-accept-message-content-<%= user.id %>';

  updateCharCountHintDirectWithClass(input_selector, '<%= hint %>', '.<%= accept_message_css_class %>');
  if ($(input_selector).val() != undefined && $(input_selector).val() !== "") {
    $(mdhtmlform_selector).show();
  }
  else {
    $(mdhtmlform_selector).hide();
  }

  $(input_selector).on('input', function () {
    if ($(this).val() !== "") {
      $(mdhtmlform_selector).fadeIn("fast");
    } else {
      $(mdhtmlform_selector).fadeOut("fast");
    }
  });
});
</script>

<h4>Schváliť organizátora</h4>

<%= simple_nested_form_for(user, url: users_manager_update_accept_message_path(user), html: { method: :post, multipart: true }) do |f| %>
  <%= f.simple_fields_for :accept_message_attributes do |m| %>
    <% css_class = "mdhtmlform-md " + accept_message_css_class %>
    <% oninput = "updateCharCountHintDirectWithClass(this, '" + hint + "', '." + accept_message_css_class + "');" %>
    <%= m.input :content, required: true, as: :text, input_html: { value: (user.accept_message != nil ? user.accept_message.content : t("simple_form.prompts.accept_message.content")), rows: 8, class: css_class, "data-mdhtmlform-group": user.id, oninput: oninput } %>
    <div id="mdhtmlform-user-accept-message-content-<%= user.id %>" class="mdhtmlform-html panel" data-mdhtmlform-group="<%= user.id %>"></div>
  <% end %>

  <ul class="st-list-unstyled st-list-inline">
    <li><%= f.submit "Schváliť", name: "accept", class: "button tiny success st-full-width" %></li>
    <li><%= f.submit "Neschváliť", name: "not_accept", class: "button tiny alert st-full-width" %></li>
  </ul>
<% end %>

app/views/users/index.html.erb
<h1>Používatelia</h1>

<h4>Používatelia (<%= @users.count %>)</h4>
<p>
  Odstránení: <%= @users.select { |u| u.paranoia_destroyed? }.count %> | Odstránení navždy: <%= User.only_deleted.users.select { |u| u.email == nil }.count %>
</p>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Meno</th>
      <th>E-mail</th>
      <th>Pohlavie</th>
      <th>Vek</th>
      <th>Mesto</th>
      <th>Krajina</th>
      <th>Priatelia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr style="<%= user.paranoia_destroyed? ? 'background-color: #CCCCCC' : '' %>">
        <td><%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px;" %></td>
        <td><%= user.get_name %></td>
        <td><%= user.email %></td>
        <td><%= user.sex.text if user.sex != nil && user.sex != "" %></td>
        <td><%= user.age %></td>
        <td><%= user.city %></td>
        <td><%= user.country.translate_name if user.country != nil %></td>
        <td><%= user.friends.count %></td>
        <% if user.email != nil %>
          <td><%= link_to 'Zobraziť', users_manager_path(user) %></td>
          <td><%= link_to 'Upraviť', edit_users_manager_path(user) %></td>
          <td>
            <% if user.paranoia_destroyed? %>
              <%= link_to 'Obnoviť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete obnoviť tohto používateľa?' } %> |
              <%= link_to 'Odstrániť navždy', users_manager_path(user, erase: true), method: :delete, data: { confirm: 'Naozaj chcete navždy odstrániť tohto používateľa?' } %>
            <% else %>
              <%= link_to 'Odstrániť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete odstrániť tohto používateľa?' } %> |
              <%= link_to 'Odstrániť navždy', users_manager_path(user, erase: true), method: :delete, data: { confirm: 'Naozaj chcete navždy odstrániť tohto používateľa?' } %>
            <% end %>
          </td>
        <% else %>
          <td colspan="3"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Pridať používateľa', new_users_manager_path(role: "user") %>
<br/><br/>


<h4>Organizátori (<%= @organizers.count %>)</h4>
<p>
  Odstránení: <%= @organizers.select { |u| u.paranoia_destroyed? }.count %>
</p>

<% @organizers.each do |user| %>
  <div id="popup-approve-user-<%= user.id %>" class="reveal-modal small" data-reveal>
    <%= render "users/accept", user: user %>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Názov</th>
      <th>E-mail</th>
      <th>Mesto</th>
      <th>Krajina</th>
      <th>Schválený</th>
      <th>Fanúšikovia</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizers.each do |user| %>
      <tr style="<%= user.paranoia_destroyed? ? 'background-color: #CCCCCC' : '' %>">
        <td><%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px;" %></td>
        <td><%= user.get_name %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= user.country.translate_name if user.country != nil %></td>
        <td><%= raw (user.accepted ? ("<span style='color:green'>" + t(:'simple_form.labels.user.accepted_true') + "</span") : ("<span style='color:red'>" + t(:'simple_form.labels.user.accepted_false') + "</span>")) %></td>
        <td><%= user.fans.count %></td>
        <td><%= link_to 'Zobraziť', users_manager_path(user) %></td>
        <td><a href="#" data-reveal-id="popup-approve-user-<%= user.id %>">Schváliť/neschváliť</a></td>
        <td><%= link_to 'Upraviť', edit_users_manager_path(user) %></td>
          <td>
            <% if user.paranoia_destroyed? %>
              <%= link_to 'Obnoviť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete obnoviť tohto používateľa?' } %>
            <% else %>
              <%= link_to 'Odstrániť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete odstrániť tohto používateľa?' } %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Pridať organizátora', new_users_manager_path(role: "organizer") %>
<br/><br/>


<h4>Artisti (<%= @artists.count %>)</h4>
<p>
  Odstránení: <%= @artists.select { |u| u.paranoia_destroyed? }.count %>
</p>

<table>
  <thead>
    <tr>
      <th>Obrázok</th>
      <th>Názov</th>
      <th>E-mail</th>
      <th>Pohlavie</th>
      <th>Typ artistu</th>
      <th>Vek</th>
      <th>Mesto</th>
      <th>Krajina</th>
      <th>Fanúšikovia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |user| %>
      <tr style="<%= user.paranoia_destroyed? ? 'background-color: #CCCCCC' : '' %>">
        <td><%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px;" %></td>
        <td><%= user.get_name %></td>
        <td><%= user.email %></td>
        <td><%= user.sex.text if user.sex != nil && user.sex != "" %></td>
        <td><%= user.artist_type.translate_name(user.sex.to_s) if user.artist_type != nil %></td>
        <td><%= user.age %></td>
        <td><%= user.city %></td>
        <td><%= user.country.translate_name if user.country != nil %></td>
        <td><%= user.fans.count %></td>
        <td><%= link_to 'Zobraziť', users_manager_path(user) %></td>
        <td><%= link_to 'Upraviť', edit_users_manager_path(user) %></td>
          <td>
            <% if user.paranoia_destroyed? %>
              <%= link_to 'Obnoviť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete obnoviť tohto používateľa?' } %>
            <% else %>
              <%= link_to 'Odstrániť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete odstrániť tohto používateľa?' } %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Pridať artistu', new_users_manager_path(role: "artist") %>
<br/><br/>


<% if @admins != nil %>
  <h4>Administrátori (<%= @admins.count %>)</h4>
  <p>
    Odstránení: <%= @admins.select { |u| u.paranoia_destroyed? }.count %>
  </p>

  <table>
    <thead>
      <tr>
        <th>Avatar</th>
        <th>E-mail</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admins.each do |user| %>
        <tr style="<%= user.paranoia_destroyed? ? 'background-color: #CCCCCC' : '' %>">
          <td><%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px;" %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Zobraziť', users_manager_path(user) %></td>
          <td><%= link_to 'Upraviť', edit_users_manager_path(user) %></td>
            <td>
              <% if user.paranoia_destroyed? %>
                <%= link_to 'Obnoviť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete obnoviť tohto používateľa?' } %>
              <% else %>
                <%= link_to 'Odstrániť', users_manager_path(user), method: :delete, data: { confirm: 'Naozaj chcete odstrániť tohto používateľa?' } %>
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Pridať administrátora', new_users_manager_path(role: "admin") %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.role.text %></h1>

<%= "Avatar" if @user.is_user? || @user.is_admin? %>
<%= "Logo" if @user.is_organizer? %>
<%= "Obrázok" if @user.is_artist? %>
<br/>
<%= link_to @user.avatar.url do %>
  <%= image_tag @user.avatar.url(:small), :style => "width: 200px; height: 200px; margin-bottom: 5px;" %></br>
<% end %>

<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>

<% if @user.is_user? %>
  <p>
    <strong>Meno:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Priezvisko:</strong>
    <%= @user.surname %>
  </p>

  <p>
    <strong>Používateľské meno:</strong>
    <%= @user.nickname %>
  </p>

  <p>
    <strong>Pohlavie:</strong>
    <%= @user.sex.text if @user.sex != nil && @user.sex != "" %>
  </p>

  <p>
    <strong>Dátum narodenia (vek):</strong>
    <% if @user.date_of_birth != nil %>
      <%= l @user.date_of_birth %> (<%= @user.age %>)
    <% end %>
  </p>

  <p>
    <strong>Adresa:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>PSČ:</strong>
    <%= @user.zip %>
  </p>

  <p>
    <strong>Mesto:</strong>
    <%= @user.city %>
  </p>

  <p>
    <strong>Krajina:</strong>
    <%= @user.country.translate_name if @user.country != nil %>
  </p>

  <p>
    <strong>Facebook profil:</strong>
    <%= @user.profile_facebook %>
  </p>

  <p>
    <strong>Google+ profil:</strong>
    <%= @user.profile_googleplus %>
  </p>

  <p>
    <strong>Twitter profil:</strong>
    <%= @user.profile_twitter %>
  </p>

  <p>
    <strong>Spotify profil:</strong>
    <%= @user.profile_spotify %>
  </p>

  <p>
    <strong>Obľúbené kategórie (<%= @likecategories.count %>):</strong>
    <ul>
      <% @likecategories.each do |category| %>
        <li><%= link_to category.translate_name, category_path(category) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Obľúbení organizátori (<%= @likeorganizers.count %>):</strong>
    <ul>
      <% @likeorganizers.each do |organizer| %>
        <li><%= image_tag organizer.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to organizer.get_name, users_manager_path(organizer) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Obľúbení artisti (<%= @likeartists.count %>):</strong>
    <ul>
      <% @likeartists.each do |artist| %>
        <li><%= image_tag artist.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to artist.get_name, users_manager_path(artist) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Priatelia (<%= @friends.count %>):</strong>
    <ul>
      <% @friends.each do |friend| %>
        <li><%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, users_manager_path(friend) %></li>
      <% end %>
    </ul>
  </p>
<% end %>


<% if @user.is_organizer? %>
  <p>
    <strong>Názov:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Krátky popis:</strong>
    <%= raw @user.markdown_short_description %>
  </p>

  <p>
    <strong>Popis:</strong>
    <%= raw @user.markdown_description %>
  </p>

  <p>
    <strong>Webová stránka:</strong>
    <%= link_to @user.web, @user.web if @user.web != nil %>
  </p>

  <p>
    <strong>Adresa:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>PSČ:</strong>
    <%= @user.zip %>
  </p>

  <p>
    <strong>Mesto:</strong>
    <%= @user.city %>
  </p>

  <p>
    <strong>Krajina:</strong>
    <%= @user.country.translate_name if @user.country != nil %>
  </p>

  <p>
    <strong>Stav profilu:</strong>
    <%= raw (@user.accepted ? ("<span style='color:green'>" + t(:'simple_form.labels.user.accepted_true') + "</span") : ("<span style='color:red'>" + t(:'simple_form.labels.user.accepted_false') + "</span>")) %>
  </p>

  <div>
    <p><strong>Schvaľovacia správa:</strong></p>
    <% if @user.accept_message != nil %>
      <p>Posledná úprava: <%= l @user.accept_message.updated_at, format: :date_and_time %></p>
      <p><%= raw @user.accept_message.markdown_content %></p>
    <% end %>
  </div>

  <p>
    <strong>Fanúšikovia (<%= @fans.count %>):</strong>
    <ul>
      <% @fans.each do |fan| %>
        <li><%= image_tag fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to fan.get_name, users_manager_path(fan) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Udalosti (<%= @events.count %>):</strong>
    <ul>
      <% @events.each do |event| %>
        <li><%= link_to event.get_title, events_manager_path(event) %></li>
      <% end %>
    </ul>
  </p>
<% end %>


<% if @user.is_artist? %>
  <p>
    <strong>Názov:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Krátky popis:</strong>
    <%= raw @user.markdown_short_description %>
  </p>

  <p>
    <strong>Popis:</strong>
    <%= raw @user.markdown_description %>
  </p>

  <p>
    <strong>Pohlavie:</strong>
    <%= @user.sex.text if @user.sex != nil && @user.sex != "" %>
  </p>

  <p>
    <strong>Typ artistu:</strong>
    <%= @user.artist_type.translate_name(@user.sex.to_s) if @user.artist_type != nil %>
  </p>

  <p>
    <strong>Dátum narodenia (vek):</strong>
    <% if @user.date_of_birth != nil %>
      <%= l @user.date_of_birth %> (<%= @user.age %>)
    <% end %>
  </p>

  <p>
    <strong>Webová stránka:</strong>
    <%= link_to @user.web, @user.web if @user.web != nil %>
  </p>

  <p>
    <strong>Adresa:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>PSČ:</strong>
    <%= @user.zip %>
  </p>

  <p>
    <strong>Mesto:</strong>
    <%= @user.city %>
  </p>

  <p>
    <strong>Krajina:</strong>
    <%= @user.country.translate_name if @user.country != nil %>
  </p>


  <p>
    <strong>Facebook profil:</strong>
    <%= @user.profile_facebook %>
  </p>

  <p>
    <strong>Google+ profil:</strong>
    <%= @user.profile_googleplus %>
  </p>

  <p>
    <strong>Twitter profil:</strong>
    <%= @user.profile_twitter %>
  </p>

  <p>
    <strong>Fanúšikovia (<%= @fans.count %>):</strong>
    <ul>
      <% @fans.each do |fan| %>
        <li><%= image_tag fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to fan.get_name, users_manager_path(fan) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Členovia (<%= @members.count %>):</strong>
    <ul>
      <% @members.each do |member| %>
        <li><%= image_tag member.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to member.get_name, users_manager_path(member) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Je členom (<%= @inverse_members.count %>):</strong>
    <ul>
      <% @inverse_members.each do |inverse_member| %>
        <li><%= image_tag inverse_member.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to inverse_member.get_name, users_manager_path(inverse_member) %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Vystupuje na udalostiach (<%= @perform_events.count %>):</strong>
    <ul>
      <% @perform_events.each do |event| %>
        <li><%= link_to event.get_title, events_manager_path(event) %></li>
      <% end %>
    </ul>
  </p>

<% end %>

<p>
  <%= link_to "Zobraziť profil", social_path(@user) %> | <%= link_to 'Upraviť', edit_users_manager_path(@user) %> | <%= link_to 'Späť', users_manager_index_path %>
</p>