config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :countries
  resources :venues
  resources :categories
  resources :artist_types

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete "remove_user_avatar", to: "registrations#remove_avatar", as: :remove_user_avatar
    post "create_news_item", to: "registrations#create_news_item", as: :create_news_item
    patch "update_news_item", to: "registrations#update_news_item", as: :update_news_item
    delete "destroy_news_item/:id", to: "registrations#destroy_news_item", as: :destroy_news_item
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  get "events_category/:category", to: "events#events_category", as: :events_category
  get "events_filter", to: "events#index", as: :events_filter
  get "events_manager_filter", to: "events_manager#index", as: :events_manager_filter

  get "list_categories", to: "categories#index", defaults: { format: "json" }
  get "list_categories/:parent_category", to: "categories#index", defaults: { format: "json" }

  get "statistics", to: "stats#index"

  resources :events do
    resources :gallery_images
  end

  resources :events_manager, controller: "events_manager" do
    resources :gallery_images
    post "update_featured", to: "events_manager#update_featured", as: :update_featured
    post "update_published", to: "events_manager#update_published", as: :update_published
    post "update_approval_message", to: "events_manager#update_approval_message", as: :update_approval_message
  end

  resources :users_manager, controller: "users_manager" do
    post "update_accept_message", to: "users_manager#update_accept_message", as: :update_accept_message
  end

  resources :admin, controller: "admin"

  resources :social, controller: "social", only: [:index, :show] do
    patch "comment_news_item", to: "social#comment_news_item", as: :comment_news_item
    patch "comment_event", to: "social#comment_event", as: :comment_event
    patch "update_comment", to: "social#update_comment", as: :update_comment
  end

  resources :likenewsitemships
  resources :friendships
  resources :fanships

end

app/controllers/social_controller.rb
class SocialController < ApplicationController
  before_action :find_user, only: [ :show ]

  before_action :authenticate_user!, except: [:show]

  layout "social"

  def index
    @users = User.users.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
    @organizers = User.organizers.select { |u| u.accepted? }.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
    @artists = User.artists.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
  end

  def show
    if !user_signed_in? && (@user.is_admin? || @user.is_user? || (@user.is_organizer? && !@user.accepted))
      redirect_to root_path, flash: { alert: I18n.t("pundit.not_authorized") }
      return
    elsif (@user != current_user && @user.is_organizer? && !@user.accepted) || @user.is_admin?
      redirect_to social_index_path, flash: { alert: I18n.t("pundit.not_authorized") }
      return
    end

    if @user.is_user?
      @likecategories = @user.likecategories.sort { |a,b| a.translate_name.downcase <=> b.translate_name.downcase }
      @likeorganizers = @user.likeorganizers.sort { |a,b| a.get_name.downcase <=> b.get_name.downcase }
      @likeartists = @user.likeartists.sort { |a,b| a.get_name.downcase <=> b.get_name.downcase }
      @friends = @user.friends.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }

      if current_user != @user
        @mutual_friends = current_user.friends.select { |u| @friends.include?(u) }.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
      end
    elsif @user.is_organizer?
      @fans = @user.fans.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
      @events = @user.events.select { |e| e.is_visible? && e.is_base_event? }.sort { |a,b| a.get_title.downcase <=> b.get_title.downcase }
    elsif @user.is_artist?
      @fans = @user.fans.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
      @members = @user.members.sort { |a,b| a.get_name.downcase <=> b.get_name.downcase }
      @inverse_members = @user.inverse_members.sort { |a,b| a.get_name.downcase <=> b.get_name.downcase }
      @perform_events = @user.perform_events.select { |e| e.is_visible? && e.is_base_event? }.sort { |a,b| a.get_title.downcase <=> b.get_title.downcase }
    end

    if current_user != @user
      @news_items = @user.news_items.ordered.select { |n| (n.parents == nil || n.parents == []) && n.event == nil && (n.news_item_visibility == :public || @user.friends.include?(current_user) || @user.fans.include?(current_user)) }
    else
      @news_items = @user.news_items.ordered.select { |n| (n.parents == nil || n.parents == []) && n.event == nil }
    end
  end

  def comment_news_item
    news_item = NewsItem.find(params[:news_item][:id])

    comment = NewsItem.create(content: params[:news_item][:news_item][:content], user: current_user)
    comment.save

    commentship = news_item.commentships.build(news_item: news_item, comment: comment)
    commentship.save

    redirect_to :back
  end

  def comment_event
    event = Event.find(params[:event][:id])

    comment = NewsItem.create(content: params[:event][:news_item][:content], user: current_user, event: event)
    comment.save

    redirect_to :back
  end

  def update_comment
    comment = NewsItem.find(params[:news_item][:id])

    if comment.user == current_user
      comment.update_attributes(content: params[:news_item][:content])
    end

    redirect_to :back
  end

  private

    def find_user
      @user = User.all.find(params[:id])
    end

end

app/helpers/social_helper.rb
module SocialHelper
end

app/views/social/_comment.html.erb
<script type="text/javascript">
$(function() {
  $("#user-news_item-update_link-<%= comment.id.to_s %>").on('click', function (e) {
    e.preventDefault();

    if ($("#user-news_item-update-<%= comment.id.to_s %>").is(":visible")) {
      $("#user-news_item-update-<%= comment.id.to_s %>").fadeOut("fast");
    }
    else {
      $("#user-news_item-update-<%= comment.id.to_s %>").fadeIn("fast");
    }
  });

  $("#user-news_item-comment_link-<%= comment.id.to_s %>").on('click', function (e) {
    e.preventDefault();

    if ($("#user-news_item-comment-<%= comment.id.to_s %>").is(":visible")) {
      $("#user-news_item-comment-<%= comment.id.to_s %>").fadeOut("fast");
    }
    else {
      $("#user-news_item-comment-<%= comment.id.to_s %>").fadeIn("fast");
    }
  });
});
</script>

<%= render "social/popup_likes", news_item: comment %>

<div style="margin: 10px; margin-left: 20px; padding: 5px; background-color: #FAFAFA;">
  <div>
    <div class="with_emoticons">
      <%= comment.content %>
    </div>
    <div style="margin-top: 5px;">
      <% if current_user != nil %>
        <%= link_to comment.user.get_name, social_path(comment.user) %>
        <%= l comment.created_at, format: :date_and_time %>
        <% if comment.updated_at != comment.created_at %>
          (upravené: <%= l comment.updated_at, format: :date_and_time %>)
        <% end %>

        <a href="#" id="user-news_item-comment_link-<%= comment.id.to_s %>">Odpovedať</a> |

        <% if comment.likenewsitems.count > 0 %>
          <a href="#" data-reveal-id="popup-likes-<%= comment.id.to_s %>"><%= comment.likenewsitems.count %> <i class="fa fa-thumbs-o-up"></i></a> |
        <% else %>
          <%= comment.likenewsitems.count %> <i class="fa fa-thumbs-o-up"></i> |
        <% end %>

        <% if comment.user == current_user %>
          <a href="#" id="user-news_item-update_link-<%= comment.id.to_s %>">Upraviť</a> |
          <%= link_to 'Odstrániť', destroy_news_item_path(comment), method: :delete, data: { confirm: 'Naozaj chcete odstrániť tento komentár?' } %><br/>
        <% else %>
          <% if !comment.likenewsitems.include?(current_user) %>
            <%= link_to likenewsitemships_path(:news_item_id => comment), :method => :post do %>
              Páči sa mi <i class="fa fa-thumbs-o-up"></i>
            <% end %>
          <% else %>
            <%= link_to likenewsitemship_path(:news_item_id => comment), :method => :delete do %>
              Už sa mi nepáči <i class="fa fa-thumbs-o-down"></i>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <%= comment.user.get_name %>
        <%= l comment.created_at, format: :date_and_time %>
        <% if comment.updated_at != comment.created_at %>
          (upravené: <%= l comment.updated_at, format: :date_and_time %>)
        <% end %>

        <%= comment.likenewsitems.count %> <i class="fa fa-thumbs-o-up"></i>
      <% end %>
    </div>
  </div>

  <% if comment.user == current_user %>
    <div id="user-news_item-update-<%= comment.id.to_s %>" style="display: none;">
      <br/>
      <%= simple_form_for(comment, url: social_update_comment_path(current_user), html: { method: :patch, multipart: true }) do |f| %>
        <%= f.input :id, as: :hidden %>
        <%= f.input :content, required: false, as: :text, hint: false, label: t(:'simple_form.labels.news_item.news_item.content'), input_html: { rows: 2 } %>
        <%= f.button :submit, t(:'helpers.submit.registrations.news_item.news_item.update'), class: "button success tiny radius" %>
      <% end %>
    </div>
  <% end %>

  <% if current_user != nil %>
    <div id="user-news_item-comment-<%= comment.id.to_s %>" style="display: none;">
      <br/>
      <%= simple_nested_form_for(comment, url: social_comment_news_item_path(current_user), html: { method: :patch, multipart: true }) do |f| %>
        <%= f.input :id, as: :hidden %>
        <%= f.simple_fields_for :news_item do |n| %>
          <%= n.input :content, required: false, as: :text, hint: false, label: t(:'simple_form.labels.news_item.news_item.content'), input_html: { rows: 2 } %>
        <% end %>

        <%= f.button :submit, t(:'helpers.submit.registrations.news_item.news_item.create'), class: "button success tiny radius" %>
      <% end %>
    </div>
  <% end %>

  <div id="user-news_item-all_comments-<%= comment.id.to_s %>">
    <% comment.comments.ordered.each do |subcomment| %>
      <%= render "social/comment", comment: subcomment %>
    <% end %>
  </div>
</div>

app/views/social/index.html.erb
<% if current_user.is_user? %>
  <h4>Všetci používatelia</h4>
  <ul>
    <% @users.each do |user| %>
      <% if current_user != user && !current_user.friends.include?(user) && user.is_user? %>
        <li>
          <%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to user.get_name, social_path(user) %>
          <% if current_user.pending_friends.include?(user) %>
            (Žiadosť o priateľstvo odoslaná, <%= link_to "Zrušiť žiadosť", friendship_path(:id => user), :method => :delete %>)
          <% elsif current_user.requested_friends.include?(user) %>
            (Prijatá žiadosť o priateľstvo, <%= link_to "Prijať", friendship_path(:id => user), :method => "put" %>, <%= link_to "Odmietnuť", friendship_path(:id => user), :method => :delete %>)
          <% else %>
            (<%= link_to "Pridať priateľa", friendships_path(:friend_id => user), :method => :post %>)
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <h4>Priatelia</h4>
  <ul>
    <% current_user.friends.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }.each do |friend| %>
      <li>
        <%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, social_path(friend) %> (<%= link_to "Zrušiť priateľstvo", friendship_path(:id => friend), :method => :delete %>)
      </li>
    <% end %>
  </ul>

  <h4>Odoslané žiadosti o priateľstvo</h4>
  <ul>
    <% current_user.pending_friends.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }.each do |friend| %>
      <% if !current_user.friends.include?(friend) %>
        <li>
          <%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, social_path(friend) %> (<%= link_to "Zrušiť žiadosť", friendship_path(:id => friend), :method => :delete %>)
        </li>
      <% end %>
    <% end %>
  </ul>

  <h4>Prijaté žiadosti o priateľstvo</h4>
  <ul>
    <% current_user.requested_friends.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }.each do |friend| %>
      <% if !current_user.friends.include?(friend) %>
        <li>
          <%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, social_path(friend) %>
          (<%= link_to "Prijať", friendship_path(:id => friend), :method => "put" %>,
          <%= link_to "Odmietnuť", friendship_path(:id => friend), :method => :delete %>)
        </li>
      <% end %>
    <% end %>
  </ul>


  <h4>Všetci organizátori</h4>
  <ul>
    <% @organizers.each do |user| %>
      <% if current_user != user && !current_user.likeorganizers.include?(user) %>
        <li>
          <%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to user.get_name, social_path(user) %> (<%= link_to "Pridať medzi obľúbených", fanships_path(:user_id => user), :method => :post %>)
        </li>
      <% end %>
    <% end %>
  </ul>

  <h4>Obľúbení organizátori</h4>
  <ul>
    <% current_user.likeorganizers.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }.each do |inverse_fan| %>
      <% if inverse_fan.accepted %>
        <li>
          <%= image_tag inverse_fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to inverse_fan.get_name, social_path(inverse_fan) %> (<%= link_to "Odstrániť z obľúbených", "fanships/" + inverse_fan.id.to_s, :method => :delete %>)
        </li>
      <% end %>
    <% end %>
  </ul>


  <h4>Všetci artisti</h4>
  <ul>
    <% @artists.each do |user| %>
      <% if current_user != user && !current_user.likeartists.include?(user) %>
        <li>
          <%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to user.get_name, social_path(user) %> (<%= link_to "Pridať medzi obľúbených", fanships_path(:user_id => user), :method => :post %>)
        </li>
      <% end %>
    <% end %>
  </ul>

  <h4>Obľúbení artisti</h4>
  <ul>
    <% current_user.likeartists.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }.each do |inverse_fan| %>
      <li>
        <%= image_tag inverse_fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to inverse_fan.get_name, social_path(inverse_fan) %> (<%= link_to "Odstrániť z obľúbených", "fanships/" + inverse_fan.id.to_s, :method => :delete %>)
      </li>
    <% end %>
  </ul>
<% end %>

app/views/social/show.html.erb
<h2><%= @user.role.text if !@user.is_user? %><%= "Profil" if @user.is_user? %></h2>

<%= link_to @user.avatar.url do %>
  <%= image_tag @user.avatar.url(:small), :style => "width: 200px; height: 200px; margin-bottom: 5px;" %></br>
<% end %>


<% if @user.is_user? %>
  <p>
    <strong>Používateľské meno:</strong>
    <%= @user.nickname %>
  </p>

  <% if @user.is_correct_real_name? %>
    <p>
      <strong>Celé meno:</strong>
      <%= @user.get_name %>
    </p>
  <% end %>

  <% if @user.sex != nil && @user.sex != "" %>
    <p>
      <strong>Pohlavie:</strong>
      <%= @user.sex.text %>
    </p>
  <% end %>

  <% if @user.date_of_birth != nil %>
    <p>
      <strong>Vek:</strong>
      <%= @user.age %>
    </p>
  <% end %>

  <% if @user.city != nil && @user.city != "" %>
    <p>
      <strong>Mesto:</strong>
      <%= @user.city %>
    </p>
  <% end %>

  <% if @user.country != nil %>
    <p>
      <strong>Krajina:</strong>
      <%= @user.country.translate_name if @user.country != nil %>
    </p>
  <% end %>

  <% if @user.profile_facebook != nil && @user.profile_facebook != "" %>
    <p>
      <strong>Facebook profil:</strong>
      <%= @user.profile_facebook %>
    </p>
  <% end %>

  <% if @user.profile_googleplus != nil && @user.profile_googleplus != "" %>
    <p>
      <strong>Google+ profil:</strong>
      <%= @user.profile_googleplus %>
    </p>
  <% end %>

  <% if @user.profile_twitter != nil && @user.profile_twitter != "" %>
    <p>
      <strong>Twitter profil:</strong>
      <%= @user.profile_twitter %>
    </p>
  <% end %>


  <% if @likecategories.count > 0 %>
    <p>
      <strong>Obľúbené kategórie (<%= @likecategories.count %>):</strong>
      <ul>
        <% @likecategories.each do |category| %>
          <li><%= link_to category.translate_name, category_path(category) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @likeorganizers.count > 0 %>
    <p>
      <strong>Obľúbení organizátori (<%= @likeorganizers.count %>):</strong>
      <ul>
        <% @likeorganizers.each do |organizer| %>
          <li><%= image_tag organizer.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to organizer.get_name, social_path(organizer) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @likeartists.count > 0 %>
    <p>
      <strong>Obľúbení artisti (<%= @likeartists.count %>):</strong>
      <ul>
        <% @likeartists.each do |artist| %>
          <li><%= image_tag artist.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to artist.get_name, social_path(artist) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @friends.count > 0 %>
    <p>
      <strong>Priatelia (<%= @friends.count %>):</strong>
      <ul>
        <% @friends.each do |friend| %>
          <li><%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, social_path(friend) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if current_user != @user && @mutual_friends.count > 0 %>
    <p>
      <strong>Spoloční priatelia (<%= @mutual_friends.count %>):</strong>
      <ul>
        <% @mutual_friends.each do |friend| %>
          <li><%= image_tag friend.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to friend.get_name, social_path(friend) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if current_user != @user %>
    <p>
      <strong>Priateľstvo:</strong><br/>
      <% if current_user.pending_friends.include?(@user) %>
        Žiadosť o priateľstvo odoslaná, <%= link_to "Zrušiť žiadosť", friendship_path(:id => @user), :method => :delete %>
      <% elsif current_user.requested_friends.include?(@user) %>
        Prijatá žiadosť o priateľstvo, <%= link_to "Prijať", friendship_path(:id => @user), :method => "put" %>, <%= link_to "Odmietnuť", friendship_path(:id => @user), :method => :delete %>
      <% elsif !current_user.friends.include?(@user) %>
        Nie ste priatelia, <%= link_to "Pridať priateľa", friendships_path(:friend_id => @user), :method => :post %>
      <% else %>
        Priatelia, <%= link_to "Zrušiť priateľstvo", friendship_path(:id => friend), :method => :delete %>
      <% end %>
    </p>
  <% end %>
<% end %>


<% if @user.is_organizer? %>
  <p>
    <strong>Názov:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Krátky popis:</strong>
    <%= raw @user.markdown_short_description %>
  </p>

  <p>
    <strong>Popis:</strong>
    <%= raw @user.markdown_description %>
  </p>

  <% if @user.web != nil && @user.web != "" %>
    <p>
      <strong>Webová stránka:</strong>
      <%= link_to @user.web, @user.web if @user.web != nil %>
    </p>
  <% end %>

  <% if (@user.address != nil && @user.address != "") ||
        (@user.zip != nil && @user.zip != "") ||
        (@user.city != nil && @user.city != "") %>
    <p>
      <strong>Adresa:</strong><br/>
      <%= @user.address %> <%= @user.zip %><br/>
      <%= @user.city %>
    </p>
  <% end %>

  <% if @user.country != nil %>
    <p>
      <strong>Krajina:</strong>
      <%= @user.country.translate_name if @user.country != nil %>
    </p>
  <% end %>

  <% if @fans.count > 0 %>
    <p>
      <strong>Fanúšikovia (<%= @fans.count %>):</strong>
      <ul>
        <% @fans.each do |fan| %>
          <li><%= image_tag fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to fan.get_name, social_path(fan) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @events.count > 0 %>
    <p>
      <strong>Udalosti (<%= @events.count %>):</strong>
      <ul>
        <% @events.select { |e| e.parent == nil }.each do |event| %>
          <li><%= link_to event.get_title, event_path(event) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
<% end %>


<% if @user.is_artist? %>
  <p>
    <strong>Názov:</strong>
    <%= @user.name %>
  </p>

  <% if @user.markdown_short_description != nil && @user.markdown_short_description != "" %>
    <p>
      <strong>Krátky popis:</strong>
      <%= raw @user.markdown_short_description %>
    </p>
  <% end %>

  <% if @user.markdown_description != nil && @user.markdown_description != "" %>
    <p>
      <strong>Popis:</strong>
      <%= raw @user.markdown_description %>
    </p>
  <% end %>

  <% if @user.sex != nil && @user.sex != "" %>
    <p>
      <strong>Pohlavie:</strong>
      <%= @user.sex.text %>
    </p>
  <% end %>

  <% if @user.artist_type != nil %>
    <p>
      <strong>Typ artistu:</strong>
      <%= @user.artist_type.translate_name(@user.sex.to_s) %>
    </p>
  <% end %>

  <% if @user.date_of_birth != nil %>
    <p>
      <strong>Vek:</strong>
      <%= @user.age %>
    </p>
  <% end %>

  <% if @user.web != nil && @user.web != "" %>
    <p>
      <strong>Webová stránka:</strong>
      <%= link_to @user.web, @user.web %>
    </p>
  <% end %>

  <% if (@user.address != nil && @user.address != "") ||
        (@user.zip != nil && @user.zip != "") ||
        (@user.city != nil && @user.city != "") %>
    <p>
      <strong>Adresa:</strong><br/>
      <%= @user.address %> <%= @user.zip %><br/>
      <%= @user.city %>
    </p>
  <% end %>

  <% if @user.country != nil %>
    <p>
      <strong>Krajina:</strong>
      <%= @user.country.translate_name %>
    </p>
  <% end %>

  <% if @user.profile_facebook != nil && @user.profile_facebook != "" %>
    <p>
      <strong>Facebook profil:</strong>
      <%= @user.profile_facebook %>
    </p>
  <% end %>

  <% if @user.profile_googleplus != nil && @user.profile_googleplus != "" %>
    <p>
      <strong>Google+ profil:</strong>
      <%= @user.profile_googleplus %>
    </p>
  <% end %>

  <% if @user.profile_twitter != nil && @user.profile_twitter != "" %>
    <p>
      <strong>Twitter profil:</strong>
      <%= @user.profile_twitter %>
    </p>
  <% end %>

  <% if @fans.count > 0 %>
    <p>
      <strong>Fanúšikovia (<%= @fans.count %>):</strong>
      <ul>
        <% @fans.each do |fan| %>
          <li><%= image_tag fan.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to fan.get_name, social_path(fan) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @members.count > 0 %>
    <p>
      <strong>Členovia (<%= @members.count %>):</strong>
      <ul>
        <% @members.each do |member| %>
          <li><%= image_tag member.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to member.get_name, social_path(member) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @inverse_members.count > 0 %>
    <p>
      <strong>Je členom (<%= @inverse_members.count %>):</strong>
      <ul>
        <% @inverse_members.each do |inverse_member| %>
          <li><%= image_tag inverse_member.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %> <%= link_to inverse_member.get_name, social_path(inverse_member) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <% if @perform_events.count > 0 %>
    <p>
      <strong>Vystupuje na udalostiach (<%= @perform_events.count %>):</strong>
      <ul>
        <% @perform_events.each do |event| %>
          <li><%= link_to event.get_title, event_path(event) %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
<% end %>


<% if @user == current_user %>
  <%= simple_nested_form_for(@user, as: "user", url: create_news_item_path, html: { method: :post, multipart: true }) do |f| %>
    <%= f.simple_fields_for :news_item do |n| %>
      <% hint = t(:"simple_form.hints.news_item.content") %>
      <% css_class = "news_item_new" %>
      <% oninput = "updateCharCountHintDirectWithClass(this, '" + hint + "', '." + css_class + "');" %>
      <% onkeyup = "$(\"#mdhtmlform-user-news_item_content_new\").emoticons();" %>
      <%= n.input :content, required: false, as: :text, hint: hint, input_html: { rows: 4, class: "mdhtmlform-md " + css_class, "data-mdhtmlform-group": "-1", oninput: oninput, onkeyup: onkeyup } %>
      <div id="mdhtmlform-user-news_item_content_new" class="mdhtmlform-html panel with_emoticons" data-mdhtmlform-group="-1"></div>
      <%= n.input :news_item_visibility, required: false, label: t(:'simple_form.labels.user.news_item_visibility'), as: :select, collection: NewsItemVisibility.all.select{ |n| ((n == :friends && @user.is_user?) || n != :friends) && ((n == :fans && (@user.is_artist? || @user.is_organizer?)) || n != :fans) }.collect { |n| [ n.text, n ] }, default: 1 %>
    <% end %>

    <%= f.button :submit, t(:'helpers.submit.registrations.news_item.create'), class: "button success tiny radius" %>
  <% end %>
<% end %>

<% @news_items.each do |news_item| %>
  <%= render "news_item", news_item: news_item %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $(".with_emoticons").emoticons();
  });
</script>