config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :countries
  resources :venues
  resources :categories
  resources :artist_types

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete "remove_user_avatar", to: "registrations#remove_avatar", as: :remove_user_avatar
    post "create_news_item", to: "registrations#create_news_item", as: :create_news_item
    patch "update_news_item", to: "registrations#update_news_item", as: :update_news_item
    delete "destroy_news_item/:id", to: "registrations#destroy_news_item", as: :destroy_news_item
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  get "events_category/:category", to: "events#events_category", as: :events_category
  get "events_filter", to: "events#index", as: :events_filter
  get "events_manager_filter", to: "events_manager#index", as: :events_manager_filter

  get "list_categories", to: "categories#index", defaults: { format: "json" }
  get "list_categories/:parent_category", to: "categories#index", defaults: { format: "json" }

  get "statistics", to: "stats#index"

  resources :events do
    resources :gallery_images
  end

  resources :events_manager, controller: "events_manager" do
    resources :gallery_images
    post "update_featured", to: "events_manager#update_featured", as: :update_featured
    post "update_published", to: "events_manager#update_published", as: :update_published
    post "update_approval_message", to: "events_manager#update_approval_message", as: :update_approval_message
  end

  resources :users_manager, controller: "users_manager" do
    post "update_accept_message", to: "users_manager#update_accept_message", as: :update_accept_message
  end

  resources :admin, controller: "admin"

  resources :social, controller: "social", only: [:index, :show] do
    patch "comment_news_item", to: "social#comment_news_item", as: :comment_news_item
    patch "comment_event", to: "social#comment_event", as: :comment_event
    patch "update_comment", to: "social#update_comment", as: :update_comment
  end

  resources :likenewsitemships
  resources :friendships
  resources :fanships

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true

  has_many :subcategories, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent, class_name: "Category"

  has_many :likecategoryships
  has_many :likeusers, :through => :likecategoryships, :source => :user

  has_many :events

  acts_as_paranoid

  def parent_categories
    categories = []
    cat = self
    while cat != nil do
      categories.append(cat)
      cat = cat.parent
    end
    categories.reverse
  end

  def is_category?(category)
    if category == nil || name == category.name
      true
    elsif parent_id != nil
      Category.with_deleted.find(parent_id).is_category?(category)
    else
      false
    end
  end

  def is_parent?(searched_parent)
    if parent_id == nil || searched_parent == nil
      false
    elsif parent_id == searched_parent
      true
    else
      Category.with_deleted.find(parent_id).is_parent?(searched_parent)
    end
  end

  def split_name
    if parent_id != nil
      Category.with_deleted.find(parent_id).split_name().append(name)
    else
      [name]
    end
  end

  def to_s
    if parent_id != nil
      Category.with_deleted.find(parent_id).to_s + " / " + translate_name
    else
      translate_name
    end
  end

  def translate_name
    I18n.t("category." + name)
  end

  def self.translate_name(name)
    I18n.t("category." + name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    respond_to do |format|
      if user_signed_in? && current_user.is_admin?
        @categories = Category.with_deleted
      else
        @categories = Category.all
      end

      format.html { @categories = @categories.sort { |a,b| a.to_s.downcase <=> b.to_s.downcase } }
      format.json do
        if params[:parent_category]
          category = nil
          if params[:parent_category] =~ /\A[-+]?[0-9]*\.?[0-9]+\Z/
            category = Category.find_by_id(params[:parent_category])
          else
            category = Category.find_by_name(params[:parent_category])
          end
          if category != nil
            render json: category.subcategories.sort { |a,b| a.translate_name.downcase <=> b.translate_name.downcase }
          end
        else
          categories = Category.where(parent: nil)
          if categories != nil
            render json: categories.sort { |a,b| a.translate_name.downcase <=> b.translate_name.downcase }
          end
        end
      end
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if user_signed_in? && current_user.is_admin?
      @events = Event.where(category: @category).sort { |a,b| a.get_full_title.downcase <=> b.get_full_title.downcase }
    else
      @events = Event.where(category: @category).select { |e| e.is_visible? }.sort { |a,b| a.get_full_title.downcase <=> b.get_full_title.downcase }
    end

    @likeusers = @category.likeusers.select { |u| u.is_user? }.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
    @likeartists = @category.likeusers.select { |u| u.is_artist? }.sort { |a,b| a.get_sort_name.downcase <=> b.get_sort_name.downcase }
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize :admin
  end

  # GET /categories/1/edit
  def edit
    authorize :admin
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    authorize :admin

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: I18n.t(:"success.messages.categories.create") }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    authorize :admin

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: I18n.t(:"success.messages.categories.update") }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize :admin

    if !@category.paranoia_destroyed?
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: I18n.t(:"success.messages.categories.destroy") }
        format.json { head :no_content }
      end
    else
      Category.restore(@category.id, :recursive => true)
      respond_to do |format|
        format.html { redirect_to categories_url, notice: I18n.t(:"success.messages.categories.restore") }
        format.json { head :no_content }
      end
    end
  end

  private

    def set_category
      @category = Category.with_deleted.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :parent_id)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_dropdown_menu.html.erb
<% i = 0 %>

<% if category != nil %>
  <% category.parent_categories.each do |c| %>
    <% i += 1 %>
    <% drop = "drop" + i.to_s %>
    <%= render "categories/dropdown_menu_button", category: c, label: c.translate_name, drop: drop %>

    <% if @category.parent_categories.last == c && c.subcategories != nil && c.subcategories.length > 0 %>
      <% i += 1 %>
      <% drop = "drop" + i.to_s %>
      <%= render "categories/dropdown_menu_button", category: c, label: t(:'category.all_categories'), drop: drop %>
    <% end %>
  <% end %>
<% end %>

<% if i == 0 %>
  <% i += 1 %>
  <% drop = "drop" + i.to_s %>
  <%= render "categories/dropdown_menu_button", category: nil, label: t(:'category.all_categories'), drop: drop %>
<% end %>

<% while i < 3 do %>
  <% i += 1 %>
  <%= render "categories/dropdown_menu_button" %>
<% end %>

app/views/categories/_dropdown_menu_button.html.erb
<% if !defined?(category) || !defined?(label) || !defined?(drop) %>
  <%= content_tag :li do %>
    <%= link_to "", class: "button split small secondary" do %>
      &nbsp;
    <% end %>
  <% end %>
<% else %>
  <%= content_tag :li do %>
    <%= link_to (category != nil ? events_manager_filter_path(category: category.name, tag: @tag, approved: @approved) : events_manager_index_path), class: "button split small secondary" do %>
      <%= label %>
      <%= content_tag(:span, nil, "data-dropdown": drop) %>
    <% end %>
  <% end %>
<% end %>

app/views/categories/_dropdown_menu_contents.html.erb
<% i = 1 %>

<% if category != nil %>
  <% category.parent_categories.each do |c| %>
    <% drop = "drop" + i.to_s %>
    <% i += 1 %>
    <%= render "categories/dropdown_menu_contents_buttons", parent: c.parent, drop: drop, all: true %>

    <% if category.parent_categories.last == c && c.subcategories != nil && c.subcategories.length > 0 %>
      <% drop = "drop" + i.to_s %>
      <%= render "categories/dropdown_menu_contents_buttons", parent: c, drop: drop, all: false %>
    <% end %>
  <% end %>
<% else %>
  <%= render "categories/dropdown_menu_contents_buttons", parent: nil, drop: "drop1", all: false %>
<% end %>

app/views/categories/_dropdown_menu_contents_buttons.html.erb
<%= content_tag(:ul, id: drop, class: "f-dropdown", "data-dropdown-content": true) do %>
  <% Category.where(parent: parent).sort { |a,b| a.translate_name.downcase <=> b.translate_name.downcase }.each do |c| %>
    <%= content_tag :li do %>
     <%= link_to c.translate_name, events_manager_filter_path(category: c.name, tag: @tag, approved: @approved) %></li>
    <% end %>
  <% end %>
  <% if all %>
    <%= content_tag :li do %>
      <%= link_to t(:'category.all_categories'), events_manager_filter_path(category: parent != nil ? parent.name : nil, tag: @tag, approved: @approved) %></li>
    <% end %>
  <% end %>
<% end %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :parent, collection: Category.all.sort { |a,b| a.to_s.downcase <=> b.to_s.downcase }.select{ |c| c != @category && !c.is_parent?(@category) }.collect { |c| [ c.to_s, c.id ] }, prompt: "Vyberte nadradenú kategóriu", include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "button success tiny" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Upraviť kategóriu</h1>

<%= render 'form' %>

<%= link_to 'Zobraziť', @category %> |
<%= link_to 'Späť', categories_path %>

app/views/categories/index.html.erb
<h1>Kategórie</h1>

<table>
  <thead>
    <tr>
      <th>Názov</th>
      <th data-tooltip class="has-tip tip-top" title="Názov vrátane nadradených kategórií">Celý názov</th>
      <th>Používatelia</th>
      <th>Artisti</th>
      <th>Udalosti</th>
      <% if current_user != nil && current_user.is_admin? %>
        <th colspan="3"></th>
      <% else %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr style="<%= category.paranoia_destroyed? ? 'background-color: #CCCCCC' : '' %>">
        <td><%= category.name %></td>
        <td><%= category.to_s %></td>
        <td>
          <%= category.likeusers.select { |u| u.is_user? }.count if category.likeusers != nil %>
        </td>
        <td>
          <%= category.likeusers.select { |u| u.is_artist? }.count if category.likeusers != nil %>
        </td>
        <td>
          <% if user_signed_in? && current_user.is_admin? %>
            <% events = Event.where(category: category) %>
          <% else %>
            <% events = Event.where(category: category).select { |e| e.is_visible? } %>
          <% end %>
          <%= events.count if events != nil %>
        </td>
        <td><%= link_to 'Zobraziť', category %></td>
        <% if current_user != nil && current_user.is_admin? %>
          <td><%= link_to 'Upraviť', edit_category_path(category) %></td>
          <td>
            <% if category.paranoia_destroyed? %>
              <%= link_to 'Obnoviť', category, method: :delete, data: { confirm: 'Naozaj chcete obnoviť túto kategóriu?' } %>
            <% else %>
              <%= link_to 'Odstrániť', category, method: :delete, data: { confirm: 'Naozaj chcete odstrániť túto kategóriu?' } %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user != nil && current_user.is_admin? %>
  <%= link_to 'Pridať kategóriu', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>Nová kategória</h1>

<%= render 'form' %>

<%= link_to 'Späť', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Názov:</strong>
  <%= @category.name %><%= @category.paranoia_destroyed? ? " (" + t(:"errors.deleted") + ")" : "" %>
</p>

<p>
  <strong>Celý názov:</strong>
  <%= @category %>
</p>

<p>
  <strong>Podradené kategórie:</strong>
  <%= @category.subcategories.map { |s| s.name }.join(", ") %>
</p>

<p>
  <strong>Používatelia, ktorí majú radi túto kategóriu (<%= @likeusers.count %>):</strong>
  <ul>
    <% @likeusers.each do |user| %>
      <% if user_signed_in? %>
        <li>
          <%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %>
          <% if current_user.is_admin? %>
            <%= link_to user.get_name, users_manager_path(user) %>
          <% else %>
            <%= link_to user.get_name, social_path(user) %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</p>

<p>
  <strong>Artisti zaradení do tejto kategórie (<%= @likeartists.count %>):</strong>
  <ul>
    <% @likeartists.each do |user| %>
      <li>
        <%= image_tag user.avatar.url(:small), :style => "width: 32px; height: 32px; margin-bottm: 5px;" %>
        <% if user_signed_in? && current_user.is_admin? %>
          <%= link_to user.get_name, users_manager_path(user) %>
        <% else %>
          <%= link_to user.get_name, social_path(user) %>
        <% end %>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Udalosti s touto kategóriou (<%= @events.count %>):</strong>
  <ul>
    <% @events.each do |event| %>
      <% if user_signed_in? && current_user.is_admin? %>
        <li><%= link_to event.get_full_title, events_manager_path(event) %></li>
      <% else %>
        <li><%= link_to event.get_full_title, event_path(event) %></li>
      <% end %>
    <% end %>
  </ul>
</p>

<% if user_signed_in? && current_user.is_admin? %>
  <%= link_to 'Upraviť', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Späť', categories_path %>